DWAPlannerROS:
  acc_lim_theta: 1.0
  acc_lim_x: 0.45
  acc_lim_y: 0.0
  acc_lim_trans: 0.45
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 22.0
  occdist_scale: 0.02
  path_distance_bias: 32 #32.0
  max_vel_theta: 0.8
  max_scaling_factor: 0.2
  max_vel_trans: 0.6
  max_vel_x: 0.6
  max_vel_y: 0.0
  min_vel_theta: 0.05
  min_vel_trans: 0.05
  min_vel_x: 0.0
  min_vel_y: 0.0
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  prune_plan: false
  restore_defaults: false
  theta_stopped_vel: 0.1
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 1.5
  stop_time_buffer: 0.2
  trans_stopped_vel: 0.1
  use_dwa: true
  vth_samples: 20
  vx_samples: 10
  vy_samples: 1
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.05
