local_costmap:

  global_frame: /odom #/odom
  robot_base_frame: /base_link
  update_frequency: 4.0 
  static_map: false

  publish_frequency: 2.0 #before 2.0

  rolling_window: true


  width: 6
  height: 6
  resolution: 0.02

  transform_tolerance: 0.5
 
  plugins:
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


